application: reddit-maze
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
- url: /drop
  script: dropper.py
  login: admin
- url: /adump
  script: dumper.py
- url: /avatar/.*
  script: avatar.py
- url: /gen
  script: gen.py
- url: .*
  script: main.py

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?tools/.*
