application: reddit-maze
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
- url: /adump
  script: dumper.py
- url: /avatar
  script: avatar.py
- url: /gen
  script: gen.py
- url: .*
  script: main.py
