application: mr-mazer
version: 1
runtime: python27
api_version: 1
threadsafe: no

builtins:
- remote_api: on

handlers:
- url: /static
  static_dir: static
- url: /drop
  script: dropper.py
  login: admin
- url: /adump
  script: dumper.py
- url: /avatar/.*
  script: avatar.py
- url: /gen
  script: gen.py
- url: .*
  script: main.py

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?tools/.*
- ^(.*/)?gae_console.py$
